language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- composer install --dev
script: vendor/bin/phpunit
matrix:
  fast_finish: true
env:
  matrix:
  - secure: kew9XiAk4s9YwgJgJAJsh6U9ItWSB7wI0/nGHotnx3VnUZ6bgH9EF+JBKkmqAjoKJpgsCrJ6Kk5/B/8CkcVhaGOQsfb/DIs0VpAOHrglK7KLtCNwXfOEHXzCLFnyudsWt+5eNih5Yf4JObF4PLGYNjhb04dcF+2zIaPgEXNvvwo=
